arch: EquiUnet
batch_size: 2
com: null
debug: false
deep_sup: false
devices: '0'
dropout: 0.0
epochs: 200
exp_name: 20221117_210533_MAT_Conv333
fold: 0
full: true
lr: 0.0001
no_fp16: false
norm_layer: group
optim: ranger
restore: false
resume: ''
seed: 16111990
start_epoch: 0
swa: true
swa_repeat: 5
val: 3
val_seg_csv_path: ./history/history_valid.csv
warm: 0
warm_restart: true
weight_decay: 0.0
width: 48
workers: 4
